server:
  port: 8008

spring:
  application:
    name: cloud-provider-payment-hystrix

eureka:
  client:
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
    #以下默认就是true，不填也行
    #fetch-registry: true
    #register-with-eureka: true
  instance:
    # 自定义服务名称信息
    instance-id: provider-payment-8008

    # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-renewal-interval-in-seconds: 1
    # 发呆时间，即服务续约到期时间（缺省为90s）
    lease-expiration-duration-in-seconds: 2
    prefer-ip-address: true