server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      # 开启从服务中心动态创建路由的功能，利用微服务名进行路由
      discovery:
        locator:
          enabled: true
      routes:
        # 路由的id，没有固定规则但要求唯一，建议配合服务名
        - id: payment_routh1
          # 匹配后提供服务的路由地址
          #uri: http://localhost:8001
          uri: lb://cloud-provider-payment
          predicates:
            # 断言，路径相匹配的进行路由
            - Path=/payment/get/**

        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://cloud-provider-payment
          predicates:
            - Path=/payment/lb/**
            #- After=2020-06-06T16:43:24.740+08:00[Asia/Shanghai]
            #- After=2020-06-07T16:43:24.740+08:00[Asia/Shanghai]
            #- Before=2020-06-06T16:43:24.740+08:00[Asia/Shanghai]
            - Before=2020-06-06T18:43:24.740+08:00[Asia/Shanghai]



eureka:
  client:
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    # 自定义服务名称信息
    instance-id: gateway-9527

    # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-renewal-interval-in-seconds: 1
    # 发呆时间，即服务续约到期时间（缺省为90s）
    lease-expiration-duration-in-seconds: 2
    prefer-ip-address: true

info:
  app.name: spring-cloud-study-v2
  company.name: www.lichangping.top
  build.artifactId: $project.artifactId$
  build.version: $project.version$
