GET http://localhost:8001/payment/get/1
Accept: application/json

###

POST http://localhost:8001/payment/create
Content-Type: application/json

{
  "serial": "Test6"
}

###

GET http://localhost:8001/payment/discovery
Accept: application/json