GET http://localhost/consumer/payment/get/2
Accept: application/json

###

POST http://localhost/consumer/payment/create
Content-Type: application/json

{
  "serial": "Test7"
}

###

GET http://localhost/consumer/payment/getForEntity/2

###

GET http://localhost/consumer/test/getForEntity/2